name: Test Gradlew

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Check gradlew
        run: |
          if [ -f gradlew ]; then
            echo "gradlew exists"
          else
            echo "gradlew NOT FOUND"
            exit 1
          fi

      - name: Grant permission
        run: chmod +x gradlew
